Add The Css and UI improvements.
Abdulwhbhussain/microverse-awesome-books pull request #2
Opened 2023-04-25 09:23 UTC by Abdulwhbhussain

2023-04-25 20:58 UTC, DuaneDave requested changes
Hi @Team👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Correct usage of es6 classes
✔️ All linters checks are fine


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 20:58 UTC, DuaneDave commented on index.js
> +  const collectionOfBooks = [];
I strongly recommend moving this into the class since you would be working a lot with the array from inside there.

2023-04-25 20:58 UTC, DuaneDave commented on index.js
> +  removeBook(collectionOfBooks) {
Please note that, when books are added, it is impossible to delete them immediately until the screen is reloaded. This behavior is likely a bug somewhere. I recommend finding it and then fixing it in order to provide a good UX.

[screen-capture.webm](https://user-images.githubusercontent.com/84930355/234401300-e1c65daf-dd66-4bb2-bc54-a5b62385429c.webm)

2023-04-26 07:37 UTC, fezzopro commented on index.js
> +  removeBook(collectionOfBooks) {
Thank you for spotting this bug @DuaneDave. The bug has been fixed

2023-04-26 10:56 UTC, fezzopro commented on index.js
> +  const collectionOfBooks = [];
Thank you for your feedback, this feedback is implemented.

2023-04-26 11:14 UTC, iambenkis approved these changes
Hi @Abdulwhbhussain , @fezzopro  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/DhstvI3zZ598Nb1rFf/giphy-downsized-medium.gif"/>
## Highlights
Linters are passing successfully ✔️
Project is running successfully ✔️
Descriptive pull request ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 16:05 UTC, merged